### PR TITLE
added RBAC

### PR DESCRIPTION
**Pull request by leahnp**
The fluent-bit container will be using the API for the metadata filter (to get info about itself) and the elasticsearch service, to send logs to storage, RBAC added to allow these actions.

### CODE REVIEW

**Comment by leahnp** [comment]
@mikeln I left it default since this is a setup for anyone's application and since we don't know what exactly will be in the pod, I didn't want to assume a namespace. If you think we should dictate a namespace preemptively, just let me know.

**Comment by mikeln** [comment]
But by making the  namespace... "default" , you are assuming the application will run in "default".  And if the app is not running in that namespace?  the rbac will have to be open enough to allow that?

By that reasoning, it would be better to place it in the kube-logging namespace like the rest of the components.   (Unless I'm missing something here...which is possible).

**Comment by leahnp** [comment]
That makes sense, amended (namespace added)

**Comment by mikeln** [comment]
ok, but now the question.   will that namespace always be present before this is installed?
do we need to worry about adding the namespace if it is not already there?

**Comment by leahnp** [comment]
I think we do need to worry about it not being there.

**Comment by mikeln** [comment]
so, create a separate `namespace.yaml` with:
```
apiVersion: v1
kind: Namespace
metadata:
  name: kube-logging
```
and make sure to install it via `kubectl --config=<blah> apply -f namespace.yaml`

`apply` will create it if isn't there, and do nothing if it is already there.  (vs. erroring out).

**Comment by leahnp** [comment]
Ya, I think you are right on apply vs create, apply seems like the safer option for users. Changes made.

**Pull request merged**
